apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  #namespace: jbg469
  name: unrestricted
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
    - NET_RAW
  volumes:
    - "*"
  hostIPC: false
  hostPID: false
  hostNetwork: false
  allowPrivilegeEscalation: false
